DROP DATABASE IF EXISTS `estudos`;

CREATE DATABASE IF NOT EXISTS `estudos`;

USE `estudos`;

CREATE TABLE `telefones` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NULL DEFAULT NULL,
    telefone VARCHAR(100) NULL DEFAULT NULL,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP()
)
